export const MOCK_CATEGORIES = [
  { id:1, slug:'imagerie-medicale',   name:'Imagerie Médicale',    icon:'🫀', description:'Équipements d\'imagerie haute performance pour un diagnostic précis', color:'#1A6FC4', products_count:4 },
  { id:2, slug:'laboratoire-medical', name:'Laboratoire Médical',  icon:'🔬', description:'Solutions complètes pour l\'analyse biologique et clinique',          color:'#27AE60', products_count:5 },
  { id:3, slug:'mobilier-hospitalier',name:'Mobilier Hospitalier', icon:'🏥', description:'Équipements ergonomiques et certifiés pour les espaces de soins',      color:'#0A3D8F', products_count:3 },
]

export const MOCK_PRODUCTS = [
  { id:1, category_id:1, slug:'scanner-multidetecteur', name:'Scanner Multidétecteur Haute Résolution', short_desc:'Imagerie tomodensitométrique de pointe, coupes ultra-fines', description:'Le scanner multidétecteur offre une résolution spatiale exceptionnelle avec des coupes de 0,5 mm. Idéal pour le diagnostic cardiovasculaire, pulmonaire et oncologique.', images:['https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&q=80'], specs:[{label:'Détecteurs',value:'64 à 256 rangées'},{label:'Résolution',value:'0,5 mm isotrope'},{label:'Vitesse rotation',value:'0,27 s/rotation'},{label:'Tension',value:'80 – 140 kV'},{label:'Garantie',value:'12 mois'}], badge:'TOP VENTE', badge_color:'#2ECC71', featured:true, active:true, category:{ name:'Imagerie Médicale', icon:'🫀' } },
  { id:2, category_id:1, slug:'irm-1-5t-3t', name:'IRM 1.5T / 3T Haute Performance', short_desc:'IRM pour diagnostic neurologique et musculosquelettique', description:'Système IRM dernière génération avec champ magnétique 1.5T ou 3T. Acquisition rapide, qualité d\'image supérieure, faible niveau sonore.', images:['https://images.unsplash.com/photo-1530026405186-ed1f139313f8?w=800&q=80'], specs:[{label:'Champ',value:'1.5T ou 3T'},{label:'Bore',value:'70 cm'},{label:'Gradient',value:'45 mT/m'},{label:'Garantie',value:'12 mois'}], badge:'NOUVEAU', badge_color:'#1A6FC4', featured:true, active:true, category:{ name:'Imagerie Médicale', icon:'🫀' } },
  { id:3, category_id:1, slug:'echographie-hd', name:'Échographie Haute Définition', short_desc:'Échographe polyvalent pour obstétrique et cardiologie', description:'Plateforme d\'échographie polyvalente avec sondes multi-fréquences. Mode Doppler couleur, élastographie et imagerie 3D/4D.', images:['https://images.unsplash.com/photo-1666214280557-f1b5022eb634?w=800&q=80'], specs:[{label:'Modes',value:'B, M, Doppler, 3D/4D'},{label:'Fréquence',value:'1 – 15 MHz'},{label:'Connectivité',value:'DICOM, Wi-Fi'},{label:'Garantie',value:'12 mois'}], badge:null, featured:false, active:true, category:{ name:'Imagerie Médicale', icon:'🫀' } },
  { id:4, category_id:1, slug:'radiologie-numerique', name:'Radiologie Numérique Haute Qualité', short_desc:'Radiographie numérique directe pour urgences et blocs', description:'Détecteur numérique plat (FPD) avec traitement automatique des images. Réduction de 70% des doses de rayonnement.', images:['https://images.unsplash.com/photo-1571772996211-2f02c9727629?w=800&q=80'], specs:[{label:'Détecteur',value:'Amorphous Silicon FPD'},{label:'Résolution',value:'3,4 lp/mm'},{label:'Réduction dose',value:'70% vs analogique'},{label:'Garantie',value:'12 mois'}], badge:null, featured:false, active:true, category:{ name:'Imagerie Médicale', icon:'🫀' } },
  { id:5, category_id:2, slug:'analyseur-hematologique', name:'Analyseur Hématologique Automatisé', short_desc:'NFS, formule leucocytaire et réticulocytes complets', description:'Automate de numération-formule sanguine avec 5 à 8 paramètres différentiels. Débit de 80 à 120 échantillons/heure.', images:['https://images.unsplash.com/photo-1579154204601-01588f351e67?w=800&q=80'], specs:[{label:'Paramètres',value:'28 à 36'},{label:'Débit',value:'80 – 120 éch/h'},{label:'Volume',value:'9 µL'},{label:'Garantie',value:'12 mois'}], badge:'TOP VENTE', badge_color:'#2ECC71', featured:true, active:true, category:{ name:'Laboratoire Médical', icon:'🔬' } },
  { id:6, category_id:2, slug:'analyseur-biochimie', name:'Analyseur de Biochimie Automatisé', short_desc:'Bilan métabolique, hépatique et rénal automatisé', description:'Automate de biochimie polyvalent avec réactifs ouverts. Analyse de 400 à 800 tests/heure.', images:['https://images.unsplash.com/photo-1530026405186-ed1f139313f8?w=800&q=80'], specs:[{label:'Débit',value:'400 – 800 tests/h'},{label:'Réactifs',value:'Système ouvert'},{label:'Connexion',value:'LIS/HIS'},{label:'Garantie',value:'12 mois'}], badge:null, featured:false, active:true, category:{ name:'Laboratoire Médical', icon:'🔬' } },
  { id:7, category_id:2, slug:'centrifugeuse-refrigeree', name:'Centrifugeuse Réfrigérée', short_desc:'Centrifugation précise pour sérum et plasma', description:'Centrifugeuse de paillasse réfrigérée (-20°C à +40°C) avec rotor interchangeable. Vitesse jusqu\'à 18 000 rpm.', images:['https://images.unsplash.com/photo-1576671081837-49000212a370?w=800&q=80'], specs:[{label:'Vitesse max',value:'18 000 rpm'},{label:'FCR max',value:'30 000 × g'},{label:'Température',value:'-20°C à +40°C'},{label:'Garantie',value:'12 mois'}], badge:null, featured:false, active:true, category:{ name:'Laboratoire Médical', icon:'🔬' } },
  { id:8, category_id:2, slug:'microscope-binoculaire', name:'Microscope Binoculaire Haute Précision', short_desc:'Microscopie avancée pour anatomopathologie', description:'Microscope binoculaire avec optiques plan-achromatiques et éclairage LED. Grossissements de 40× à 1000×.', images:['https://images.unsplash.com/photo-1628595351029-c2bf17511435?w=800&q=80'], specs:[{label:'Grossissement',value:'40× – 1000×'},{label:'Éclairage',value:'LED 3W'},{label:'Optiques',value:'Plan-achromatiques'},{label:'Garantie',value:'12 mois'}], badge:'NOUVEAU', badge_color:'#1A6FC4', featured:false, active:true, category:{ name:'Laboratoire Médical', icon:'🔬' } },
  { id:9, category_id:2, slug:'analyse-urine', name:'Système d\'Analyse d\'Urine', short_desc:'Bandelettes et sédiment urinaire automatisés par IA', description:'Automate d\'urinalyse avec module bandelette et sédiment intégrés. Classification automatique des éléments figurés.', images:['https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&q=80'], specs:[{label:'Débit',value:'500 – 1000 éch/h'},{label:'Paramètres',value:'10 – 14'},{label:'Connexion',value:'LIS bidirectionnel'},{label:'Garantie',value:'12 mois'}], badge:null, featured:false, active:true, category:{ name:'Laboratoire Médical', icon:'🔬' } },
  { id:10, category_id:3, slug:'table-operation', name:'Table d\'Opération Électrique Multiposition', short_desc:'Table chirurgicale motorisée plateau carbone', description:'Table d\'opération à commande électrique avec plateau radiotransparent. Mouvements motorisés : Trendelenburg ±30°.', images:['https://images.unsplash.com/photo-1551190822-a9333d879b1f?w=800&q=80'], specs:[{label:'Charge max',value:'250 kg'},{label:'Plateau',value:'Carbone radiotransparent'},{label:'Positions',value:'Trendelenburg ±30°'},{label:'Garantie',value:'12 mois'}], badge:null, featured:false, active:true, category:{ name:'Mobilier Hospitalier', icon:'🏥' } },
  { id:11, category_id:3, slug:'lit-medicalise', name:'Lit Médicalisé à Hauteur Variable', short_desc:'Lit hospitalier motorisé pour soins intensifs', description:'Lit médicalisé avec réglage motorisé de la hauteur, du dossier et des pieds. Pèse-personne intégré.', images:['https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&q=80'], specs:[{label:'Hauteur plancher',value:'35 – 80 cm'},{label:'Charge max',value:'200 kg'},{label:'Normes',value:'EN 60601-2-52'},{label:'Garantie',value:'12 mois'}], badge:null, featured:false, active:true, category:{ name:'Mobilier Hospitalier', icon:'🏥' } },
  { id:12, category_id:3, slug:'chariot-soins', name:'Chariot de Soins Inox Modulable', short_desc:'Chariot anti-corrosion pour bloc opératoire', description:'Chariot de soins en acier inoxydable 304 avec plateaux amovibles et tiroirs sécurisés par serrure à code.', images:['https://images.unsplash.com/photo-1576671081837-49000212a370?w=800&q=80'], specs:[{label:'Matériau',value:'Inox 304'},{label:'Plateaux',value:'2 à 4 niveaux'},{label:'Charge totale',value:'80 kg'},{label:'Garantie',value:'12 mois'}], badge:null, featured:false, active:true, category:{ name:'Mobilier Hospitalier', icon:'🏥' } },
]

export const MOCK_STATS = {
  products_count: 12, categories_count: 3,
  views_total: 1247, contacts_total: 34,
}
