export const MOCK_CATEGORIES = [
  { id:1, slug:'produits-laitiers',    name:'Produits Laitiers',    icon:'🥛', description:'Lait, beurre et fromages fermiers issus de notre troupeau élevé en plein air', color:'#4A7C2F', products_count:4 },
  { id:2, slug:'viandes-charcuterie',  name:'Viandes & Charcuterie', icon:'🥩', description:'Viandes fermières et charcuterie artisanale, élevage respectueux du bien-être animal', color:'#5E9E2E', products_count:5 },
  { id:3, slug:'oeufs-volaille',       name:'Œufs & Volaille',      icon:'🥚', description:'Œufs plein air et volailles fermières nourries au grain', color:'#2E5A1F', products_count:3 },
]

export const MOCK_PRODUCTS = [
  { id:1, category_id:1, slug:'lait-cru-fermier', name:'Lait Cru Fermier', short_desc:'Lait cru entier, collecté chaque matin à la ferme', description:'Notre lait cru fermier provient de vaches élevées en pâturage. Riche et onctueux, il conserve tout son goût naturel et ses qualités nutritionnelles.', images:['https://divinform.com/img/vie3.jpg'], specs:[{label:'Conditionnement',value:'Bouteille 1 L'},{label:'Conservation',value:'4°C, 72h'},{label:'Origine',value:'Ferme Divinform'},{label:'Type',value:'Lait cru entier'}], badge:'TOP VENTE', badge_color:'#86C34A', featured:true, active:true, category:{ name:'Produits Laitiers', icon:'🥛' } },
  { id:2, category_id:1, slug:'beurre-fermier', name:'Beurre Fermier', short_desc:'Beurre de baratte artisanal au bon goût de crème', description:'Beurre fermier baratté de façon traditionnelle à partir de notre crème fraîche. Texture fondante et saveur authentique.', images:['https://divinform.com/img/vie3.jpg'], specs:[{label:'Conditionnement',value:'Motte 250 g'},{label:'Conservation',value:'4°C, 3 semaines'},{label:'Type',value:'Doux ou demi-sel'},{label:'Origine',value:'Ferme Divinform'}], badge:'NOUVEAU', badge_color:'#4A7C2F', featured:true, active:true, category:{ name:'Produits Laitiers', icon:'🥛' } },
  { id:3, category_id:1, slug:'yaourt-fermier', name:'Yaourt Fermier Nature', short_desc:'Yaourts onctueux au lait entier de la ferme', description:'Yaourts fermiers fabriqués avec notre lait entier, sans additifs. Doux et crémeux, à déguster nature ou avec du miel.', images:['https://divinform.com/img/vie3.jpg'], specs:[{label:'Conditionnement',value:'Pot 125 g x4'},{label:'Conservation',value:'4°C'},{label:'Type',value:'Nature au lait entier'},{label:'Origine',value:'Ferme Divinform'}], badge:null, featured:false, active:true, category:{ name:'Produits Laitiers', icon:'🥛' } },
  { id:4, category_id:1, slug:'fromage-fermier', name:'Fromage Fermier Affiné', short_desc:'Fromage à pâte pressée affiné en cave', description:'Fromage fermier au lait cru affiné plusieurs semaines dans notre cave. Caractère prononcé et croûte naturelle.', images:['https://divinform.com/img/vie3.jpg'], specs:[{label:'Conditionnement',value:'Portion 300 g'},{label:'Affinage',value:'6 à 10 semaines'},{label:'Lait',value:'Cru de vache'},{label:'Origine',value:'Ferme Divinform'}], badge:null, featured:false, active:true, category:{ name:'Produits Laitiers', icon:'🥛' } },
  { id:5, category_id:2, slug:'colis-viande-bovine', name:'Colis de Viande Bovine', short_desc:'Colis de bœuf fermier, morceaux variés', description:'Colis de viande bovine issu de notre élevage en pâturage. Assortiment de morceaux à griller, à rôtir et à mijoter, sous vide.', images:['https://divinform.com/img/vie3.jpg'], specs:[{label:'Poids',value:'5 kg'},{label:'Conditionnement',value:'Sous vide'},{label:'Élevage',value:'Plein air'},{label:'Origine',value:'Ferme Divinform'}], badge:'TOP VENTE', badge_color:'#86C34A', featured:true, active:true, category:{ name:'Viandes & Charcuterie', icon:'🥩' } },
  { id:6, category_id:2, slug:'saucisses-fermieres', name:'Saucisses Fermières', short_desc:'Saucisses artisanales préparées à la ferme', description:'Saucisses fermières préparées de façon artisanale à partir de nos porcs élevés en plein air. Sans conservateurs ajoutés.', images:['https://divinform.com/img/vie3.jpg'], specs:[{label:'Conditionnement',value:'Barquette 500 g'},{label:'Conservation',value:'4°C'},{label:'Élevage',value:'Plein air'},{label:'Origine',value:'Ferme Divinform'}], badge:null, featured:false, active:true, category:{ name:'Viandes & Charcuterie', icon:'🥩' } },
  { id:7, category_id:2, slug:'pate-de-campagne', name:'Pâté de Campagne', short_desc:'Pâté artisanal à l\'ancienne', description:'Pâté de campagne préparé selon une recette traditionnelle, à base de viande fermière. Généreux et parfumé.', images:['https://divinform.com/img/vie3.jpg'], specs:[{label:'Conditionnement',value:'Terrine 200 g'},{label:'Conservation',value:'4°C'},{label:'Recette',value:'Traditionnelle'},{label:'Origine',value:'Ferme Divinform'}], badge:null, featured:false, active:true, category:{ name:'Viandes & Charcuterie', icon:'🥩' } },
  { id:8, category_id:2, slug:'jambon-fermier', name:'Jambon Fermier Sec', short_desc:'Jambon sec affiné longuement', description:'Jambon fermier salé au sel sec et affiné avec patience. Une charcuterie de caractère au goût authentique.', images:['https://divinform.com/img/vie3.jpg'], specs:[{label:'Affinage',value:'9 mois'},{label:'Conditionnement',value:'À la coupe'},{label:'Élevage',value:'Plein air'},{label:'Origine',value:'Ferme Divinform'}], badge:'NOUVEAU', badge_color:'#4A7C2F', featured:false, active:true, category:{ name:'Viandes & Charcuterie', icon:'🥩' } },
  { id:9, category_id:2, slug:'rillettes-fermieres', name:'Rillettes Fermières', short_desc:'Rillettes fondantes préparées maison', description:'Rillettes fermières cuisinées à la ferme, fondantes et savoureuses. Parfaites à tartiner à l\'apéritif.', images:['https://divinform.com/img/vie3.jpg'], specs:[{label:'Conditionnement',value:'Pot 180 g'},{label:'Conservation',value:'4°C'},{label:'Recette',value:'Maison'},{label:'Origine',value:'Ferme Divinform'}], badge:null, featured:false, active:true, category:{ name:'Viandes & Charcuterie', icon:'🥩' } },
  { id:10, category_id:3, slug:'oeufs-plein-air', name:'Œufs Plein Air', short_desc:'Œufs frais de poules élevées en plein air', description:'Œufs fermiers pondus par nos poules élevées en plein air et nourries au grain. Jaune généreux et goût authentique.', images:['https://divinform.com/img/vie3.jpg'], specs:[{label:'Conditionnement',value:'Boîte de 6'},{label:'Calibre',value:'Moyen à gros'},{label:'Élevage',value:'Plein air'},{label:'Origine',value:'Ferme Divinform'}], badge:null, featured:false, active:true, category:{ name:'Œufs & Volaille', icon:'🥚' } },
  { id:11, category_id:3, slug:'poulet-fermier', name:'Poulet Fermier', short_desc:'Poulet élevé en plein air, nourri au grain', description:'Poulet fermier élevé en liberté et nourri au grain. Chair ferme et savoureuse pour un rôti dominical réussi.', images:['https://divinform.com/img/vie3.jpg'], specs:[{label:'Poids',value:'1,6 à 2 kg'},{label:'Élevage',value:'Plein air'},{label:'Alimentation',value:'Grain'},{label:'Origine',value:'Ferme Divinform'}], badge:null, featured:false, active:true, category:{ name:'Œufs & Volaille', icon:'🥚' } },
  { id:12, category_id:3, slug:'oeufs-caille', name:'Œufs de Caille', short_desc:'Petits œufs de caille délicats', description:'Œufs de caille fermiers, parfaits pour l\'apéritif et les recettes raffinées. Délicats et savoureux.', images:['https://divinform.com/img/vie3.jpg'], specs:[{label:'Conditionnement',value:'Boîte de 12'},{label:'Élevage',value:'Plein air'},{label:'Alimentation',value:'Grain'},{label:'Origine',value:'Ferme Divinform'}], badge:null, featured:false, active:true, category:{ name:'Œufs & Volaille', icon:'🥚' } },
]

export const MOCK_STATS = {
  products_count: 12, categories_count: 3,
  views_total: 1247, contacts_total: 34,
}
